POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post.",
  "category": "Technology",
  "tags": ["Tech", "Programming"]
}

###

PUT http://localhost:8080/posts/1
Content-Type: application/json

{
  "title": "My Updated Blog Post",
  "content": "This is the updated content of my first blog post.",
  "category": "Technology",
  "tags": ["Tech", "Programming"]
}

###

DELETE http://localhost:8080/posts/1

###

GET http://localhost:8080/posts/1

###

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts?term=tech
